---

- name: 'Copy service'
  copy:
    src: /home/arsen/project-ansible/roles/systemd/res/web-app.service
    dest: /lib/systemd/system
    owner: root
    group: root

- name: 'Enable/Start Service'
  systemd:
    name: 'web-app'
    daemon_reload: yes
    enabled: yes
    state: 'started'